version: '3.8'

services:
    traefik:
        image: traefik:v2.9
        command: --api.insecure=true --providers.docker
        ports:
            - "80:80"
            - "8080:8080"
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.redirect-to-http.redirectscheme.scheme=http"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
    app:
        container_name: dedikam
        labels:
            - "traefik.http.routers.app.rule=Host(`app.localhost`)"
        depends_on:
            - traefik
            - database
#        env_file:
#            - .env.production
        build:
            dockerfile: Dockerfile
            context: .
#        volumes:
#            - .:/var/www/html
    database:
        image: postgres
        container_name: postgres
        restart: always
        volumes:
            - postgresql:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: dedikam
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgAdmin
        restart: always
        ports:
            - "5050:80"
            - "5051:443"
        depends_on:
            - database
        environment:
            PGADMIN_DEFAULT_EMAIL: mr.vanced2@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password

volumes:
    postgresql:
