@extends('layouts.app')
@section('content')
<div class="container-sm overflow-hidden p-0">
    <div class="row mx-2 mx-sm-0 g-2 text-center m-3">
        <div class="alert alert-primary fs-3 fw-bolder" role="alert">
            <span>CONDITIONS GÉNÉRALES D'UTILISATION ET DE VENTE</span>
        </div>
    </div>
    <div class="row mx-2 mx-sm-0">
        <p>En visitant notre site et/ou en commandant quelque chose auprès de notre association, vous prenez part à notre « Service » et acceptez d’être lié(e) par les modalités et conditions suivantes (« Conditions générales de vente»), y compris par les modalités, conditions et politiques mentionnées aux présentes et/ou accessibles en hyperlien. Les présentes conditions d’utilisation s’appliquent à tous les utilisateurs du site, y compris, sans s’y limiter, aux individus qui sont des visiteurs, des fournisseurs, des clients, des marchands et/ou des fournisseurs de contenu.Veuillez lire attentivement les présentes Conditions d’utilisation avant d’accéder à notre site web et de l’utiliser. En accédant à une quelconque partie du site ou en l’utilisant, vous acceptez d’être lié(e) par les présentes conditions d’utilisation. Si vous n’acceptez pas la totalité des modalités et conditions du présent accord, vous ne pourrez peut-être pas accéder au site web ou utiliser ses services. Si les présentes conditions d’utilisation sont considérées comme une offre, leur acceptation se limite expressément à elles.</p>
        <p>Chacun des nouveaux services ou fonctionnalités qui sont ajoutés au site sont également assujettis aux conditions d’utilisation. Vous pouvez consulter la version la plus récente des conditions d’utilisation à tout moment sur cette page. Nous nous réservons le droit de mettre à jour, modifier ou remplacer n’importe quelle partie des présentes conditions d’utilisation en publiant lesdites mises à jour et/ou modifications sur notre site web. Il vous incombe de vérifier cette page de temps à autre pour voir si des changements y ont été apportés. En continuant à accéder au site web ou à l’utiliser après la publication des modifications, vous acceptez celles-ci.</p>
        <h4>1 – CONDITIONS D’UTILISATION DU SITE EN LIGNE</h4>
        <p>En acceptant les présentes conditions d’utilisation, vous déclarez avoir atteint ou dépassé l’âge de la majorité dans votre région, province ou état et nous avoir donné l’autorisation de permettre à toute personne mineure à votre charge d’utiliser ce site.</p>
        <p>Vous ne devez en aucune façon utiliser nos produits à des fins illégales ou non autorisées, ni violer des lois de votre juridiction lorsque vous utilisez le Service (y compris, sans toutefois s’y limiter, les lois relatives aux droits d’auteur).</p>
        <p>Vous ne devez pas transmettre de vers informatique, de virus ou tout code de nature destructrice.</p>
        <p>Une infraction ou une violation de n’importe laquelle des conditions entraînera la résiliation immédiate de vos services.</p>
        <h4>2 – CONDITIONS GÉNÉRALES</h4>
        <p>Nous nous réservons le droit de refuser de servir quelqu’un à tout moment et pour quelque raison que ce soit.</p>
        <p>Vous comprenez que votre contenu (à l’exception des informations relatives à votre carte de crédit) peut être transféré sans chiffrement et que cela comprend des transmissions sur plusieurs réseaux et des changements effectués dans le but de se conformer et de s’adapter aux exigences techniques de la connexion de réseaux ou d’appareils. Les informations de votre carte de crédit sont toujours chiffrées lors de leur transfert sur les réseaux.</p>
        <p>Vous acceptez de ne pas reproduire, dupliquer, copier, vendre, revendre ou exploiter toute partie du Service, toute utilisation du Service ou tout accès aux services, ou encore tout contact sur le site web à travers lequel le Service est fourni, sans notre autorisation écrite expresse.</p>
        <p>Les titres utilisés dans le présent accord sont inclus à titre indicatif uniquement et ne limiteront ni n’affecteront aucunement ces Conditions.</p>
        <h4>3 – EXACTITUDE, EXHAUSTIVITÉ ET ACTUALITÉ DES INFORMATIONS</h4>
        <p>Nous ne saurions être tenus responsables si les informations proposées sur ce site sont inexactes, incomplètes ou caduques. Le contenu de ce site est fourni à titre d’information générale uniquement et ne doit pas être considéré ou utilisé comme seule base pour la prise de décisions sans consulter des sources d’information plus importantes, plus exactes, plus complètes ou plus actuelles. Si vous vous fiez au contenu de ce site, vous le faites à vos propres risques.</p>
        <p>Ce site peut contenir certaines données historiques. Par définition, les données historiques ne sont pas actuelles et sont fournies uniquement à titre de référence. Nous nous réservons le droit de modifier les contenus de ce site à tout moment, mais nous n’avons aucune obligation de mettre à jour les informations qu’il contient, quelles qu’elles soient. Vous reconnaissez qu’il vous incombe de surveiller les changements apportés à notre site.</p>
        <h4>4 – MODIFICATIONS DU SERVICE ET DES PRIX</h4>
        <p>Les prix de nos services sont modifiables sans préavis.</p>
        <p>Nous nous réservons le droit de modifier ou de mettre fin au service (ou à une quelconque partie de celui-ci) à tout moment et sans préavis.</p>
        <p>Nous ne pourrons être tenus responsables envers vous ou tout tiers de tout changement de prix, ou encore de toute modification, suspension ou interruption du service.</p>
        <h4>5 – SERVICES</h4>
        <p>Tous les services sont disponibles qu’en ligne à travers le site web.</p>
        <p>Nous nous sommes efforcés de présenter aussi précisément que possible les couleurs et images des services figurant sur le site. Nous ne pouvons cependant pas garantir la précision d’affichage des couleurs sur l’écran de votre ordinateur. Nous nous réservons le droit, sans toutefois y être obligés, de limiter la vente de nos produits ou Services à n’importe quelle personne, région géographique ou juridiction donnée. Nous nous autorisons à exercer ce droit au cas par cas. Nous nous réservons le droit de limiter les quantités des produits ou services que nous offrons. Toutes les descriptions des produits et leur tarification sont modifiables à tout moment, sans préavis et à notre entière discrétion. Nous nous réservons le droit d’interrompre la vente d’un produit à tout moment. Toute offre de produit ou service sur ce site est nulle là où la loi l’interdit.</p>
        <p>Nous ne garantissons pas que la qualité des services que vous commandez répondra à vos attentes ni que les erreurs que comporte éventuellement le Service seront corrigées.</p>
        <h4>6 – EXACTITUDE DE LA FACTURATION ET DES INFORMATIONS DE COMPTE</h4>
        <p>Nous nous réservons le droit de refuser toute commande que vous passez auprès de nous. Nous pouvons, à notre seule discrétion, limiter ou annuler les quantités achetées par personne, par foyer ou par commande. Ces restrictions peuvent inclure les commandes passées par ou sur le même compte client, la même carte de crédit et/ou des commandes utilisant la même adresse de facturation et/ou d’expédition. Si nous modifions ou annulons une commande, il se peut que nous tentions de vous en aviser en vous contactant au moyen de l’adresse e-mail et/ou de l’adresse de facturation ou du numéro de téléphone fournis au moment de la commande. Nous nous réservons le droit de limiter ou d’interdire les commandes qui, selon nous, semblent avoir été passées par des négociants, des revendeurs ou des distributeurs.Vous acceptez de fournir des informations d’achat et de compte actuelles, complètes et exactes pour tous les achats effectués sur notre site. Vous acceptez de mettre rapidement à jour votre compte et toute autre information, y compris votre adresse e-mail et vos numéros de cartes de crédit et leurs dates d’expiration, afin que nous puissions finaliser vos transactions et vous contacter en cas de besoin.</p>
        <h4>7 – OUTILS FACULTATIFS</h4>
        <p>Nous sommes susceptibles de vous fournir l’accès à des outils tiers que nous ne surveillons, ne contrôlons et ne gérons pas.</p>
        <p>Vous reconnaissez et acceptez que nous vous fournissons l’accès à ces outils « tels quels », sans garantie, représentation ou condition d’aucune sorte et sans la moindre approbation. Nous ne saurions être tenus responsables de quoi que ce soit à l’égard de ce qui pourrait résulter de ou être relié à votre utilisation des outils facultatifs tiers.</p>
        <p>Toute utilisation par vous des outils facultatifs proposés par le biais du site est entièrement à votre discrétion et à vos propres risques. En outre, il vous appartient de vous renseigner sur les conditions dans lesquelles ces outils sont fournis par le(s) fournisseur(s) tiers concerné(s) et accepter ces conditions.</p>
        <p>Il se peut également qu’à l’avenir, nous proposions de nouveaux services et/ou de nouvelles fonctionnalités à travers le site web (y compris le lancement de nouveaux outils et ressources). Ces nouveaux services et/ou fonctionnalités seront aussi assujettis aux présentes conditions d’utilisations.</p>
        <h4>8 – LIENS DE TIERS</h4>
        <p>Certains contenus, produits et services accessibles via notre service peuvent inclure des éléments provenant de tiers.</p>
        <p>Les liens de tiers sur ce site peuvent vous rediriger vers des sites web de tiers qui ne sont pas affiliés à nous. Nous ne sommes pas tenus d’examiner ou d’évaluer leur contenu ou leur exactitude, de même que nous ne garantissons pas et n’assumons aucune responsabilité quant aux contenus ou sites web, ou aux autres contenus, produits ou services de sources tierces.</p>
        <p>Nous ne sommes pas responsables des préjudices ou dommages liés à l’achat ou à l’utilisation de biens, services, ressources, contenus ou de toute autre transaction reliée à ces sites web tiers. Veuillez lire attentivement les politiques et pratiques de ces tiers et assurez-vous de bien les comprendre avant de vous engager dans une transaction. Les plaintes, réclamations, préoccupations ou questions concernant les produits de tiers doivent être adressées à ces mêmes tiers.</p>
        <h4>9 – COMMENTAIRES, RETOURS D’EXPÉRIENCE ET AUTRES SOUMISSIONS</h4>
        <p>Si, à notre demande, vous soumettez des contenus spécifiques (par exemple, dans le cadre de votre participation à des concours), ou si, sans demande de notre part, vous envoyez des idées créatives, des suggestions, des propositions, des plans ou d’autres éléments, que ce soit en ligne, par e-mail, par courrier ou autrement, vous nous accordez le droit, à tout moment et sans restriction, de modifier, copier, publier, distribuer, traduire et utiliser dans quelque média que ce soit tous les commentaires que vous nous transmettez. Nous ne sommes pas et ne devrons en aucun cas être tenus de maintenir la confidentialité des commentaires, de dédommager qui que ce soit pour tout commentaire fourni et de répondre aux commentaires. Nous pouvons, mais nous n’en avons pas l’obligation, supprimer le contenu et les Comptes contenant du contenu que nous jugeons, à notre seule discrétion, illégal, offensant, menaçant, diffamatoire, pornographique, obscène ou autrement répréhensible ou qui viole la propriété intellectuelle d’une partie ou les présentes Conditions d’utilisation.Vous convenez que vos commentaires ne doivent en aucun cas porter atteinte aux droits de tiers, y compris aux droits d’auteur, aux marques de commerce, à la vie privée, à la personnalité ou à tout autre droit personnel ou de propriété intellectuelle. Vous convenez en outre que vos commentaires ne devront contenir aucun élément illégal, injurieux ou obscène, ni aucun virus informatique ou autre logiciel malveillant susceptible d’affecter d’une quelconque façon le fonctionnement du Service ou de tout site web connexe. Vous ne pouvez pas utiliser de fausse adresse e-mail, prétendre être quelqu’un que vous n’êtes pas, ou essayer de nous induire, nous ou les tiers, en erreur quant à l’origine des commentaires. Vous êtes entièrement responsable de tous les commentaires que vous émettez ainsi que de leur exactitude. Nous déclinons toute responsabilité à l’égard des commentaires publiés par vous ou un tiers.</p>
        <h4>10 – INFORMATIONS PERSONNELLES</h4>
        <p>La transmission de vos informations personnelles sur notre site est régie par notre Politique de confidentialité. Cliquez ici pour consulter notre Politique de Confidentialité.</p>
        <h4>11 – ERREURS, INEXACTITUDES ET OMISSIONS</h4>
        <p>Il se peut qu’il y ait parfois, sur notre site ou dans les services, des informations contenant des erreurs typographiques, des inexactitudes ou des omissions reliées aux descriptions, aux prix, aux services et aux offres. Nous nous réservons le droit de corriger toute erreur, inexactitude ou omission, et de changer ou d’actualiser des informations, voire d’annuler des commandes si une quelconque information dans le service ou sur tout site web connexe est inexacte, et ce, à tout moment et sans préavis (y compris après que vous ayez passé votre commande).</p>
        <p>Nous ne sommes pas tenus d’actualiser, de modifier ou de clarifier les informations indiquées dans les services ou sur tout site web connexe, y compris mais sans s’y limiter, les informations sur les prix, sauf si la loi l’exige. Aucune date précise de mise à jour ou d’actualisation appliquée aux services ou à tout site web connexe ne saurait être définie pour indiquer que l’ensemble des informations offertes dans les services ou sur tout site web connexe ont été modifiées ou mises à jour.</p>
        <h4>12 – UTILISATIONS INTERDITES</h4>
        <p>En plus des autres interdictions énoncées dans les Conditions d’utilisation, il vous est interdit d’utiliser le site ou son contenu :</p>
        <p>à des fins illégales, pour inciter des tiers à réaliser des actes illégaux ou à y prendre part, pour enfreindre toute ordonnance locale ou toute réglementation, règle ou loi internationale, fédérale, provinciale ou étatique, pour transgresser ou violer nos droits de propriété intellectuelle ou ceux de tiers, pour harceler, maltraiter, insulter, blesser, diffamer, calomnier, dénigrer, intimider ou discriminer quiconque en fonction du sexe, de l’orientation sexuelle, de la religion, de l’origine ethnique, de la race, de l’âge, de l’origine nationale ou d’un handicap, pour soumettre des renseignements faux ou trompeurs, pour mettre en ligne ou transmettre des virus ou tout autre type de code malveillant qui sera ou pourrait être utilisé en vue de compromettre la fonctionnalité ou le fonctionnement du Service ou de tout site web connexe, ainsi que d’autres sites web ou d’Internet, pour recueillir ou suivre les renseignements personnels d’autrui, pour spammer, hameçonner, détourner un domaine, extorquer des informations, parcourir, explorer ou balayer le web à des fins obscènes ou immorales ou pour perturber ou contourner les mesures de sécurité du service ou de tout site connexe, ainsi que d’autres sites web ou d’Internet. Nous nous réservons le droit de mettre fin à votre utilisation du service ou de tout site web connexe pour avoir enfreint les interdits en matière d’utilisation.</p>
        <h4>13 – EXCLUSION DE GARANTIES ET LIMITATION DE RESPONSABILITÉ</h4>
        <p>Nous ne garantissons, certifions ou déclarons en aucun cas que votre utilisation de notre Service sera ininterrompue, sécurisée, sans délai ou sans erreur.</p>
        <p>Nous ne garantissons pas que les résultats qui pourraient être obtenus en utilisant le Service seront exacts ou fiables.</p>
        <p>Vous acceptez que, de temps à autre, nous puissions retirer le service pour des périodes indéterminées ou l’annuler à tout moment et sans préavis.Vous convenez expressément que votre utilisation du Service, ou votre incapacité à utiliser celui-ci, est à votre seul risque. Le service ainsi que tous les produits et services qui vous sont fournis par le biais de celui-ci sont (sauf mention expresse de notre part) fournis « tels quels » et « sous réserve de disponibilité » pour votre utilisation, et ce, sans représentation, garanties ou conditions d’aucune sorte, soit expresses soit implicites, y compris toutes les garanties ou conditions implicites de commercialisation ou de qualité marchande, d’adaptation à un usage particulier, de durabilité, de titre et d’absence de contrefaçon. L’association Dedikam, responsables, employés, sociétés affiliées, stagiaires, fournisseurs, prestataires de services et concédants ne peuvent en aucun cas être tenus responsables de toute blessure, perte, réclamation, ou de quelconques dommages directs, indirects, accessoires, punitifs, spéciaux ou consécutifs, y compris mais sans s’y limiter, de la perte de profits, revenus, économies ou données, de coûts de remplacement ou autres dommages similaires, qu’ils soient contractuels, délictuels (même en cas de négligence), de responsabilité stricte ou autre, résultant de votre utilisation du service ou de tout service ou produit recourant à celui-ci, ou de toute autre réclamation liée de quelque manière que ce soit à votre utilisation du service ou de tout produit, y compris mais sans s’y limiter, à des erreurs ou omissions dans un contenu, ou à de quelconques pertes ou dommages découlant de l’utilisation du service ou d’un contenu (ou produit) publié, transmis ou rendu accessible par le biais du service, et ce, même si vous avez été averti(e) de la possibilité qu’ils surviennent.Du fait que certains états ou juridictions ne permettent pas d’exclure ou de limiter la responsabilité quant aux dommages consécutifs ou accessoires, notre responsabilité dans ces états ou juridictions sera limitée dans la mesure maximale permise par la loi.</p>
        <h4>14 – INDEMNISATION</h4>
        <p>Vous acceptez d’indemniser, de défendre et de tenir l’association Dedikam, partenaires, responsables, directeurs, prestataires de services, stagiaires et employés, quittes de toute réclamation ou demande, y compris d’honoraires raisonnables d’avocat, émise par un quelconque tiers à cause de ou consécutivement à votre violation des présentes Conditions d’utilisation ou des documents auxquels elles font référence, ou à votre violation de quelconques lois ou droits d’un tiers.</p>
        <h4>15 – DISSOCIABILITÉ</h4>
        <p>Dans le cas où une quelconque disposition des présentes conditions d’utilisation est jugée illégale, nulle ou inapplicable, cette disposition sera néanmoins applicable dans la pleine mesure permise par la loi, et la partie non applicable sera considérée comme étant dissociée de ces Conditions d’utilisation, sans que ce jugement n’affecte la validité et l’applicabilité des autres dispositions.</p>
        <h4>16 – RÉSILIATION</h4>
        <p>Les obligations et responsabilités engagées par les parties avant la date de résiliation resteront en vigueur après la résiliation de cet accord, et ce, à toutes fins.</p>
        <p>Les présentes conditions d’utilisation resteront en vigueur, à moins et jusqu’à ce qu’elles soient résiliées par vous ou par nous. Vous pouvez résilier ces conditions d’utilisation à tout moment en nous avisant que vous ne souhaitez plus utiliser nos Services, ou lorsque vous cessez d’utiliser notre site. Si nous jugeons ou suspectons, à notre seule discrétion, que vous ne respectez pas ou que vous n’avez pas respecté une quelconque modalité ou disposition des présentes conditions d’utilisation, nous pouvons également résilier cet accord à tout moment et sans préavis. Vous demeurerez alors responsable de toutes les sommes redevables jusqu’à la date de résiliation (incluse), en conséquence de quoi nous pouvons vous refuser l’accès à nos Services (ou à une partie de ceux-ci).</p>
        <h4>17 – INTÉGRALITÉ DE L’ACCORD</h4>
        <p>Tout manquement de notre part à l’exercice ou à l’application d’un droit ou d’une disposition des présentes Conditions d’utilisation ne constitue pas une renonciation à ce droit ou à cette disposition.</p>
        <p>Les présentes conditions d’utilisation ou toute autre politique ou règle d’exploitation que nous publions sur ce site ou qui concernent le Service constituent l’intégralité de l’entente et de l’accord entre vous et nous, et régissent votre utilisation du service. Elles remplacent l’ensemble des accords, communications et propositions antérieurs et actuels, oraux ou écrits, entre vous et nous (y compris, mais sans s’y limiter, toute version antérieure des conditions d’utilisation).Toute ambiguïté quant à l’interprétation de ces conditions d’utilisation ne doit pas être interprétée en défaveur de la partie rédactrice.</p>
        <h4>18 – LOI APPLICABLE</h4>
        <p>Les présentes Conditions d’utilisation, ainsi que tout accord distinct par lequel nous vous fournissons les services sont régis et interprétés en vertu des lois de la communauté de Rouen.</p>
        <h4>19 – MODIFICATIONS APPORTÉES AUX CONDITIONS D’UTILISATION</h4>
        <p>Vous pouvez consulter la version la plus récente des Conditions d’utilisation à tout moment sur cette page.</p>
        <p>Nous nous réservons le droit, à notre seule discrétion, de mettre à jour, modifier ou remplacer toute partie des présentes conditions d’utilisation en publiant lesdites mises à jour et/ou modifications sur notre site web. Il vous incombe de vérifier notre site web de temps à autre pour voir si des changements y ont été apportés. En continuant à accéder à notre site web et au service ou à les utiliser après la publication de modifications apportées aux présentes Conditions d’utilisation, vous acceptez celles-ci.</p>
        <h4>20 – COORDONNÉES</h4>
        <p>Les questions relatives aux conditions d’utilisation doivent nous être envoyées à : <span id="eeb-621096-503655">support@dedikam.com</span><script type="text/javascript">document.getElementById("eeb-621096-503655").innerHTML = eval(decodeURIComponent("%27%73%75%70%70%6f%72%74%40%64%65%64%69%6b%61%6d%2e%63%6f%6d%27"))</script><noscript>*protected email*</noscript></p>
        <h4>21 – VALIDATION DE LA COMMANDE</h4>
        <p>Toute commande figurant sur le site Internet suppose l’adhésion aux présentes conditions Générales. Toute confirmation de commande entraîne votre adhésion pleine et entière aux présentes conditions générales de vente, sans exception ni réserve.&nbsp; L’ensemble des données fournies et la confirmation enregistrée vaudront preuve de la transaction.</p>
        <p>Vous déclarez en avoir parfaite connaissance.&nbsp;</p>
        <p>Un récapitulatif des informations de votre commande et des présentes conditions générales, vous sera communiqué via l’adresse e-mail de confirmation de votre commande.</p>
        <h4>22 – PAIEMENT</h4>
        <p>Le fait de valider votre commande implique pour vous l’obligation de payer le prix indiqué.</p>
        <p>Le règlement de vos commandes s’effectue par carte bancaire grâce aux systèmes sécurisés Stripe et PayPal ou par Virement Bancaire.</p>
</div>

@endsection


